import Head from 'next/head';
import React from 'react';
import Header from './Header';
import SiderLeft from './SiderLeft';
import style from '../styles/Design.module.css';
import { Col, Row } from 'reactstrap';
import News from './News';
import Covid from './Covid';

const Design: React.FC = () => {
  return (
    <>
      <Head>
          <title>News</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Row className={style.content}>
        <Col md={2}><SiderLeft/></Col>
        <Col md={7}><News/></Col>
        <Col md={3}><Covid/></Col>
      </Row>
    </>
  );
}

export default Design;