import Head from 'next/head';
import React from 'react';
import Header from './Header';
import SiderLeft from './SiderLeft';
import Covid from './Covid';
import style from '../styles/Design.module.css';
import { Col, Row } from 'reactstrap';

const Design: React.FC = ({children}) => {
  return (
    <>
      <Head>
          <title>Next News</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Row className={style.content}>
        <Col xs={1} md={2}><SiderLeft/></Col>
        <Col xs={8} md={7}>{children}</Col>
        <Col xs={3}><Covid/></Col>
      </Row>
    </>
  );
}

export default Design;