export const FETCH_DATA = "FETCH_DATA";
export const FETCH_DATA_COVID = "FETCH_DATA_COVID";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAIL = "FETCH_FAIL";
export const FETCH_COVID_SUCCESS = "FETCH_COVID_SUCCESS";
